FROM python:3.12-alpine3.22
RUN apk add --no-cache unfs3 rpcbind
COPY profiles/agent.py /app/agent.py
ENTRYPOINT ["python3", "/app/agent.py"]
COPY profiles/test_agent.py /app/test_agent.py
RUN cd /app && python3 -m unittest test_agent -v && rm test_agent.py
