FROM python:3.12-alpine3.22
RUN apk add --no-cache unfs3 rpcbind openssh-client
RUN pip install --no-cache-dir pexpect==4.9.0
COPY profiles/*.py /app/
ENTRYPOINT ["python3", "/app/agent.py"]
RUN cd /app && python3 -m unittest discover -p 'test_*.py' -v && rm test_*.py
